// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // A single autogenerated sidebar built from the docs/ tree + _category_.json.
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
